networks:
  overlay:

services:
  mysql:
    image: bitnami/mysql:8.3
    restart: always
    env_file: docker-compose/mysql.env
    environment:
      # TODO remove the next line when we support the new auth plugin
      MYSQL_EXTRA_FLAGS: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - mysql-db:/var/lib/mysql
      - ./db_structure.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./seeds.sql:/docker-entrypoint-initdb.d/02-initdata.sql:ro
    networks:
      - overlay
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  app:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      target: development
    command: ["npm", "start"]
    volumes:
      # Note: only files in src will be updated; for all code outside src we must rebuild the image
      - ./src:/app/src
    init: true
    env_file:
      - docker-compose/app.env
    networks:
      - overlay
    ports:
      - 8080:8080


volumes:
  mysql-db:
