networks:
  reader:

services:
  mysql_init:
    image: biblemesh/shibboleth-common:1.0.0-dev
    depends_on:
      - common
    build:
      context: .
      dockerfile: Dockerfile.certs
    environment:
      - EREADER_HOST=read.test
      - SHIBBOLETH_IDENTITY_PROVIDER_HOST=op-sp-1.test  # FIXME use env file
    volumes:
      - ./add-data-to-sql-file.sh:/data/entrypoint.sh:ro
      - ./seeds.sql:/data/seeds.sql:ro
      - mysql-init-script:/data/output:rw
    command: ["/data/entrypoint.sh"]
  mysql:
    image: bitnami/mysql:8.0.40
    depends_on:
      mysql_init:
        condition: service_completed_successfully
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PORT_NUMBER: ${DATABASE_PORT}
      # TODO remove the next line when we support the new auth plugin
      MYSQL_EXTRA_FLAGS: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - mysql-db:/bitnami/mysql/data
      - ./db_structure.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - type: volume
        source: mysql-init-script
        target: /docker-entrypoint-initdb.d/02-initdata.sql
        read_only: true
        volume:
          nocopy: true
          subpath: 02-initdata.sql
    networks:
      - reader
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  reader:
    image: biblemesh/toad-reader-server
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      target: development
    command: ["npm", "start"]
    volumes:
      - ./app.js:/app/app.js
      - ./src:/app/src
    init: true
    environment:
      - USE_DEVELOPMENT_S3=1
      - APP_PATH=${APP_PATH:-/index.html}
      - APP_URL=${APP_URL}
      - AUTH_METHOD_OVERRIDE=${AUTH_METHOD_OVERRIDE:-}
      - CLOUDFRONT_KEY_PAIR_ID=${CLOUDFRONT_KEY_PAIR_ID}
      - CLOUDFRONT_PRIVATE_KEY=${CLOUDFRONT_PRIVATE_KEY}
      - DEV_NETWORK_IP=${DEV_NETWORK_IP:-localhost}
      - DEFAULT_DOMAIN_TO_QUERY_FOR_EMAIL=${DEFAULT_DOMAIN_TO_QUERY_FOR_EMAIL}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - IS_DEV=${IS_DEV:-}
      - IS_STAGING=${IS_STAGING}
      - LOGIN_TEST_CODE=${LOGIN_TEST_CODE:-}
      - LOGIN_TEST_EMAIL=${LOGIN_TEST_EMAIL:-}
      - LOGLEVEL=${LOGLEVEL}
      - OVERRIDE_DATABASE_NAME=${OVERRIDE_DATABASE_NAME:-}
      - OVERRIDE_DATABASE_HOSTNAME=${OVERRIDE_DATABASE_HOSTNAME:-}
      - OVERRIDE_DATABASE_PASSWORD=${OVERRIDE_DATABASE_PASSWORD:-}
      - OVERRIDE_DATABASE_PORT=${OVERRIDE_DATABASE_PORT:-}
      - OVERRIDE_DATABASE_USERNAME=${OVERRIDE_DATABASE_USERNAME:-}
      - PORT=${PORT:-8080}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - REQUIRE_HTTPS=${REQUIRE_HTTPS:-}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - SES_ACCESS_KEY_ID=${SES_ACCESS_KEY_ID}
      - SES_AWS_REGION=${SES_AWS_REGION}
      - SES_SECRET_ACCESS_KEY=${SES_SECRET_ACCESS_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-secret}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - WHITELISTED_EMAILS=${WHITELISTED_EMAILS}
    networks:
      - reader
    restart: always

  minio:
    image: minio/minio:latest
    volumes:
      - minio-data:/data
    ports:
      - "9001:9001"
    networks:
      - reader
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

  create_buckets:
    image: minio/mc:latest
    depends_on:
      - minio
    networks:
      - reader
    entrypoint: >
      /bin/sh -c '
      set -e;
      sleep 5;
      /usr/bin/mc config host add s3 http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} --api S3v4;
      /usr/bin/mc mb --ignore-existing s3/${S3_BUCKET};
      exit 0;
      '

include:
  - path: git@github.com:biblemesh/ereader-callback.git#16d35c3cc24b858910a9a7a7c1bb5ef14a0aeb52
    env_file: .env.callback
  - path: git@github.com:biblemesh/shibboleth.git#70e2f68fae56cab4c93ad36d04b4bb50eed4dd72:.devcontainer/shibboleth/docker-compose.yml
    env_file: .env.shibboleth

volumes:
  mysql-init-script:
  mysql-db:
  minio-data:
