networks:
  reader:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

services:
  mysql:
    image: bitnami/mysql:8.0.40
    restart: always
    env_file: docker-compose/mysql.env
    environment:
      # TODO remove the next line when we support the new auth plugin
      MYSQL_EXTRA_FLAGS: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - mysql-db:/bitnami/mysql/data
      - ./db_structure.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./seeds.sql:/docker-entrypoint-initdb.d/02-initdata.sql:ro
    networks:
      - reader
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  reader:
    image: biblemesh/reader
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      target: development
    command: ["npm", "start"]
    volumes:
      - ./app.js:/app/app.js
      - ./src:/app/src
    init: true
    env_file:
      - docker-compose/app.env
    networks:
      - reader

include:
  - git@github.com:biblemesh/ereader-callback.git#16d35c3cc24b858910a9a7a7c1bb5ef14a0aeb52

volumes:
  mysql-db:
