org: booklane
app: toad-reader-server
service: toad-reader-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  role: arn:aws:iam::767398079027:role/toad-reader-server

functions:
  api:
    handler: app.handler
    memorySize: 2048  # mb
    timeout: 29  # the HTTP API request times out at 30 seconds; so 29 seconds is the max I can set this to
    events:
      - httpApi: '*'
    environment:
      APP_URL: ${param:APP_URL}
      CLOUDFRONT_KEY_PAIR_ID: ${param:CLOUDFRONT_KEY_PAIR_ID}
      CLOUDFRONT_PRIVATE_KEY: ${param:CLOUDFRONT_PRIVATE_KEY}
      DEFAULT_FROM_EMAIL: ${param:DEFAULT_FROM_EMAIL}
      IS_STAGING: ${param:IS_STAGING}
      LOGIN_TEST_CODE: ${param:LOGIN_TEST_CODE}
      LOGIN_TEST_EMAIL: ${param:LOGIN_TEST_EMAIL}
      LOGLEVEL: ${param:LOGLEVEL}
      DATABASE_NAME: ${param:DATABASE_NAME}
      DATABASE_HOSTNAME: ${param:DATABASE_HOSTNAME}
      DATABASE_PASSWORD: ${param:DATABASE_PASSWORD}
      DATABASE_PORT: ${param:DATABASE_PORT}
      DATABASE_USERNAME: ${param:DATABASE_USERNAME}
      REQUIRE_HTTPS: ${param:REQUIRE_HTTPS}
      S3_ACCESS_KEY_ID: ${param:S3_ACCESS_KEY_ID}
      S3_BUCKET: ${param:S3_BUCKET}
      S3_SECRET_ACCESS_KEY: ${param:S3_SECRET_ACCESS_KEY}
      SES_ACCESS_KEY_ID: ${param:SES_ACCESS_KEY_ID}
      SES_AWS_REGION: ${param:SES_AWS_REGION}
      SES_SECRET_ACCESS_KEY: ${param:SES_SECRET_ACCESS_KEY}
      SESSION_SECRET: ${param:SESSION_SECRET}
      SUPPORT_EMAIL: ${param:SUPPORT_EMAIL}
  crons:
    handler: crons.handler
    # memorySize: 2048  # mb
    timeout: 60  # 1 minute
    events:
      - schedule: rate(1 minute)
    environment:
      IS_STAGING: ${param:IS_STAGING}
      DATABASE_NAME: ${param:DATABASE_NAME}
      DATABASE_HOSTNAME: ${param:DATABASE_HOSTNAME}
      DATABASE_PASSWORD: ${param:DATABASE_PASSWORD}
      DATABASE_PORT: ${param:DATABASE_PORT}
      DATABASE_USERNAME: ${param:DATABASE_USERNAME}
      DEFAULT_FROM_EMAIL: ${param:DEFAULT_FROM_EMAIL}
      REQUIRE_HTTPS: ${param:REQUIRE_HTTPS}
      S3_BUCKET: ${param:S3_BUCKET}
      SESSION_SECRET: ${param:SESSION_SECRET}

package:
  exclude:
    - .env
