name: Lint / Test / Build

on:
  pull_request:
  push:
    branches:
      - 8/set-up-ci


env:
  DEFAULT_NODE_VERSION: 16.x

permissions:
  contents: read
  #deployments: write
  #packages: write

jobs:

  build:
    name: ${{ matrix.action }} (${{ matrix.node-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]
        action: [lint, build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Docker meta
        if: matrix.action == 'build' && matrix.node-version == env.DEFAULT_NODE_VERSION
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_SET_OUTPUT_ENV: "true"
        with:
          images: |
            ghcr.io/${{ github.repository }}
            ${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Set variables for ci:build
        if: matrix.action == 'build'
        run: |
          echo $DOCKER_METADATA_OUTPUT_JSON | jq -r '"DOCKER_TAGS=\"-t " + (.tags | join(" -t ")) + "\""' >> $GITHUB_ENV
          echo $DOCKER_METADATA_OUTPUT_JSON | jq -r '"REVISION=" + (.labels."org.opencontainers.image.revision")' >> $GITHUB_ENV
          echo $DOCKER_METADATA_OUTPUT_JSON | jq -r '"TAG_VERSION_NUMBER=" + (.labels."org.opencontainers.image.version")' >> $GITHUB_ENV
          echo $DOCKER_METADATA_OUTPUT_JSON | jq -r '"DATETIMENOW=" + (.labels."org.opencontainers.image.created")' >> $GITHUB_ENV

      - name: ci:${{ matrix.action }}
        shell: bash
        run: npm run ci:${{ matrix.action }}
        env:
          GITHASH: ${{ github.sha }}
          GITHUB_REPO: ${{ github.repository }}
          BASE_BRANCH: ${{ github.base_ref || 'bm-develop' }}
          NODE_VERSION: ${{ matrix.node-version }}

      - name: Login to GitHub Container Registry
        if: matrix.action == 'build' && matrix.node-version == env.DEFAULT_NODE_VERSION
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        if: matrix.action == 'build' && matrix.node-version == env.DEFAULT_NODE_VERSION
        run: |
          export IMAGE_NAME=$(docker images --format {{.Repository}} | head -n1 | grep ghcr.io)
          echo IMAGE_NAME=$IMAGE_NAME
          if [ ! "$IMAGE_NAME" == "" ]; then docker push "$IMAGE_NAME" --all-tags; fi
